[package]
name = "additional-accounts-request"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anchor-lang = { version="0.28.0", features=["event-cpi"]}
bytemuck = "1.8.0"
sokoban = "0.3.1"