[package]
name = "bs58-pubkey"
version = "0.1.0"
edition = "2021"

[dependencies]
anchor-lang = { git = "https://github.com/ngundotra/anchor", branch = "events", features=["event-cpi"]}
bs58 = "0.5.0"
serde = { version = "1.0.163", features = ["derive"] }
serde_json = "1.0"